import "./globals.css";
import { Roboto_Flex } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoFlex = Roboto_Flex({
  preload: true,
  subsets: ["latin"],
  variable: "--main-font",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={robotoFlex.variable}>
      <body>{children}</body>
    </html>
  );
}
